using System.Data;
using DBAPulse.Domain;
using Microsoft.Data.SqlClient;

namespace DBAPulse.Data;

public sealed class CapacityStore
{
    private readonly string _connectionString;
    public CapacityStore(string connectionString) => _connectionString = new SqlConnectionStringBuilder(connectionString) { InitialCatalog = "DBA_PULSE" }.ConnectionString;
    public Task<CapacityOverview?> OverviewAsync(CancellationToken token) => OneAsync("dbo.usp_Capacity_Overview", null, r => new CapacityOverview(Dec(r,"TotalDatabaseSizeMb"),Dec(r,"Growth30dMb"),I(r,"DatabaseWarningCount"),I(r,"DatabaseCriticalCount"),I(r,"VolumeWarningCount"),I(r,"VolumeCriticalCount"),I(r,"ForecastableDatabaseCount"),I(r,"InsufficientDataCount"),DecNullable(r,"NearestExhaustionDays")), token);
    public async Task<PagedResult<CapacityDatabaseRow>> DatabasesAsync(string? status,int? serverId,string? forecastStatus,int page,int pageSize,CancellationToken token,int? databaseId=null)
    {
        var result = await PagedAsync("dbo.usp_Capacity_Databases", c => { Add(c,"@Status",status); Add(c,"@ServerId",serverId); Add(c,"@ForecastStatus",forecastStatus); Add(c,"@DatabaseId",databaseId); c.Parameters.AddWithValue("@PageNumber",page); c.Parameters.AddWithValue("@PageSize",Math.Clamp(pageSize,1,100)); }, r => new CapacityDatabaseRow(I(r,"DatabaseId"),S(r,"DatabaseName"),S(r,"ServerName"),Dec(r,"CurrentDataSizeMb"),Dec(r,"CurrentLogSizeMb"),Dec(r,"CurrentTotalSizeMb"),DecNullable(r,"Growth7dMb"),DecNullable(r,"Growth30dMb"),DecNullable(r,"Growth90dMb"),DecNullable(r,"GrowthRateMbPerDay"),DecNullable(r,"Forecast30dMb"),DecNullable(r,"Forecast90dMb"),DecNullable(r,"RSquared"),I(r,"SampleCount"),I(r,"HistoryDays"),S(r,"ForecastStatus"),S(r,"CapacityStatus"),UtcNullable(r,"LastCollectedAtUtc"),S(r,"DataFreshness")),token);
        var calculated = await Task.WhenAll(result.Items.Select(async x => CapacityForecastCalculator.Apply(x, await HistoryAsync(x.DatabaseId, 365, token))));
        return result with { Items = calculated };
    }
    public Task<IReadOnlyList<CapacityHistoryRow>> HistoryAsync(int databaseId,int days,CancellationToken token) => ManyAsync("dbo.usp_Capacity_DatabaseHistory", c=>{c.Parameters.AddWithValue("@DatabaseId",databaseId);c.Parameters.AddWithValue("@Days",new[]{7,30,90,180,365}.Contains(days)?days:30);}, r=>new CapacityHistoryRow(Utc(r,"CollectedAtUtc"),Dec(r,"DataSizeMb"),Dec(r,"LogSizeMb"),Dec(r,"TotalSizeMb"),DecNullable(r,"ForecastTotalSizeMb"),S(r,"SeriesType")),token);
    public Task<PagedResult<VolumeCapacityRow>> VolumesAsync(string? status,int? serverId,string? forecastStatus,int page,int pageSize,CancellationToken token,string? volumeId=null) => PagedAsync("dbo.usp_Capacity_Volumes", c=>{Add(c,"@Status",status);Add(c,"@ServerId",serverId);Add(c,"@ForecastStatus",forecastStatus);Add(c,"@VolumeId",volumeId);c.Parameters.AddWithValue("@PageNumber",page);c.Parameters.AddWithValue("@PageSize",Math.Clamp(pageSize,1,100));},r=>new VolumeCapacityRow(Long(r,"Id"),I(r,"ServerId"),S(r,"ServerName"),S(r,"VolumeId"),Long(r,"TotalBytes"),Long(r,"AvailableBytes"),Dec(r,"FreePercent"),DecNullable(r,"GrowthBytesPerDay"),DecNullable(r,"EstimatedExhaustionDays"),S(r,"ForecastStatus"),S(r,"CapacityStatus"),I(r,"SampleCount"),Utc(r,"CollectedAtUtc"),S(r,"DataFreshness")),token);
    private async Task<PagedResult<T>> PagedAsync<T>(string name,Action<SqlCommand> add,Func<SqlDataReader,T> map,CancellationToken token){await using var c=await OpenAsync(token);await using var cmd=Procedure(c,name);add(cmd);await using var r=await cmd.ExecuteReaderAsync(token);var items=new List<T>();while(await r.ReadAsync(token))items.Add(map(r));var total=0;if(await r.NextResultAsync(token)&&await r.ReadAsync(token))total=I(r,"TotalCount");return new(items,Convert.ToInt32(cmd.Parameters["@PageNumber"].Value),Convert.ToInt32(cmd.Parameters["@PageSize"].Value),total);}
    private async Task<T?> OneAsync<T>(string name,Action<SqlCommand>? add,Func<SqlDataReader,T> map,CancellationToken token) where T:class{await using var c=await OpenAsync(token);await using var cmd=Procedure(c,name);add?.Invoke(cmd);await using var r=await cmd.ExecuteReaderAsync(token);return await r.ReadAsync(token)?map(r):null;}
    private async Task<IReadOnlyList<T>> ManyAsync<T>(string name,Action<SqlCommand> add,Func<SqlDataReader,T> map,CancellationToken token){await using var c=await OpenAsync(token);await using var cmd=Procedure(c,name);add(cmd);await using var r=await cmd.ExecuteReaderAsync(token);var rows=new List<T>();while(await r.ReadAsync(token))rows.Add(map(r));return rows;}
    private async Task<SqlConnection> OpenAsync(CancellationToken token){var c=new SqlConnection(_connectionString);await c.OpenAsync(token);return c;}
    private static SqlCommand Procedure(SqlConnection c,string n)=>new(n,c){CommandType=CommandType.StoredProcedure,CommandTimeout=60}; private static void Add(SqlCommand c,string n,object? v)=>c.Parameters.AddWithValue(n,v??DBNull.Value); private static int I(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?0:Convert.ToInt32(r[n]); private static long Long(SqlDataReader r,string n)=>Convert.ToInt64(r[n]); private static decimal Dec(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?0:Convert.ToDecimal(r[n]); private static decimal? DecNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Convert.ToDecimal(r[n]); private static string S(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?string.Empty:Convert.ToString(r[n])??string.Empty; private static DateTimeOffset Utc(SqlDataReader r,string n)=>new(DateTime.SpecifyKind(Convert.ToDateTime(r[n]),DateTimeKind.Utc)); private static DateTimeOffset? UtcNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Utc(r,n);
}
