using System.Data;
using DBAPulse.Domain;
using Microsoft.Data.SqlClient;

namespace DBAPulse.Data;

public sealed class ProtectionStore
{
    private readonly string _connectionString;
    public ProtectionStore(string connectionString) => _connectionString = new SqlConnectionStringBuilder(connectionString) { InitialCatalog = "DBA_PULSE" }.ConnectionString;

    public Task<ProtectionOverview?> OverviewAsync(CancellationToken token) => OneAsync("dbo.usp_ProtectionAvailability_Overview", null, r => new ProtectionOverview(I(r,"ProtectedDatabaseCount"),I(r,"BackupWarningCount"),I(r,"BackupCriticalCount"),I(r,"BackupUnknownCount"),I(r,"AlwaysOnHealthyCount"),I(r,"AlwaysOnWarningCount"),I(r,"AlwaysOnCriticalCount"),I(r,"FailedJobCount"),I(r,"RunningJobCount"),I(r,"LongRunningJobCount")), token);
    public Task<PagedResult<BackupProtectionRow>> BackupsAsync(string? status,int? serverId,int? databaseId,string? recoveryModel,int page,int pageSize,CancellationToken token) => PagedAsync("dbo.usp_BackupProtection_List", c => { Add(c,"@Status",status); Add(c,"@ServerId",serverId); Add(c,"@DatabaseId",databaseId); Add(c,"@RecoveryModel",recoveryModel); c.Parameters.AddWithValue("@PageNumber",page); c.Parameters.AddWithValue("@PageSize",Math.Min(100,Math.Max(1,pageSize))); }, r => new BackupProtectionRow(I(r,"DatabaseId"),S(r,"DatabaseName"),S(r,"ServerName"),S(r,"RecoveryModel"),S(r,"DatabaseStatus"),S(r,"ProtectionStatus"),Date(r,"LastFull"),Date(r,"LastDiff"),Date(r,"LastLog"),LongNullable(r,"BackupAgeMinutes"),LongNullable(r,"LogBackupAgeMinutes"),UtcNullable(r,"LastCollected"),S(r,"DataFreshness"),S(r,"Environment"),S(r,"BackupProtectionMode"),B(r,"BackupRequired"),B(r,"IsMirrored"),S(r,"ProtectionScopeReason")), token);
    public Task<PagedResult<AlwaysOnHealthRow>> AlwaysOnAsync(string? health,int? serverId,string? role,string? syncState,int page,int pageSize,CancellationToken token,long? id=null) => PagedAsync("dbo.usp_AlwaysOnHealth_List", c => { Add(c,"@Health",health); Add(c,"@ServerId",serverId); Add(c,"@Role",role); Add(c,"@SynchronizationState",syncState); Add(c,"@Id",id); c.Parameters.AddWithValue("@PageNumber",page); c.Parameters.AddWithValue("@PageSize",Math.Min(100,Math.Max(1,pageSize))); }, r => new AlwaysOnHealthRow(Long(r,"Id"),S(r,"ServerName"),S(r,"AvailabilityGroupName"),SNullable(r,"ReplicaServerName"),SNullable(r,"Role"),SNullable(r,"OperationalState"),SNullable(r,"ConnectedState"),SNullable(r,"SynchronizationHealth"),SNullable(r,"DatabaseName"),SNullable(r,"SynchronizationState"),SNullable(r,"DatabaseState"),B(r,"IsSuspended"),SNullable(r,"SuspendReason"),DecNullable(r,"LogSendQueueMb"),DecNullable(r,"RedoQueueMb"),DecNullable(r,"EstimatedLagMinutes"),Utc(r,"CollectedAtUtc"),S(r,"HealthStatus"),S(r,"DataFreshness")), token);
    public Task<PagedResult<JobHealthRow>> JobsAsync(string? status,int? serverId,bool? enabled,bool? repeated,bool? running,int page,int pageSize,CancellationToken token,long? id=null) => PagedAsync("dbo.usp_JobHealth_List", c => { Add(c,"@Status",status); Add(c,"@ServerId",serverId); Add(c,"@Enabled",enabled); Add(c,"@RepeatedFailure",repeated); Add(c,"@Running",running); Add(c,"@Id",id); c.Parameters.AddWithValue("@PageNumber",page); c.Parameters.AddWithValue("@PageSize",Math.Min(100,Math.Max(1,pageSize))); }, r => new JobHealthRow(Long(r,"Id"),S(r,"ServerName"),S(r,"JobId"),S(r,"JobName"),B(r,"Enabled"),S(r,"LastRunStatus"),Date(r,"LastRunAtSource"),IntNullable(r,"LastRunDurationSeconds"),B(r,"IsRunning"),Date(r,"CurrentStartAtSource"),IntNullable(r,"CurrentDurationSeconds"),I(r,"FailureCount24Hours"),I(r,"FailureCount7Days"),B(r,"RepeatedFailure"),B(r,"IsLongRunning"),Utc(r,"CollectedAtUtc"),S(r,"DataFreshness")), token);

    private async Task<PagedResult<T>> PagedAsync<T>(string name, Action<SqlCommand> add, Func<SqlDataReader,T> map, CancellationToken token)
    { await using var c=await OpenAsync(token); await using var cmd=Procedure(c,name); add(cmd); await using var r=await cmd.ExecuteReaderAsync(token); var items=new List<T>(); while(await r.ReadAsync(token)) items.Add(map(r)); var total=0; if(await r.NextResultAsync(token)&&await r.ReadAsync(token)) total=I(r,"TotalCount"); var page=cmd.Parameters.Contains("@PageNumber")?Convert.ToInt32(cmd.Parameters["@PageNumber"].Value):1; var size=cmd.Parameters.Contains("@PageSize")?Convert.ToInt32(cmd.Parameters["@PageSize"].Value):50; return new(items,page,size,total); }
    private async Task<T?> OneAsync<T>(string name,Action<SqlCommand>? add,Func<SqlDataReader,T> map,CancellationToken token) where T:class { await using var c=await OpenAsync(token); await using var cmd=Procedure(c,name); add?.Invoke(cmd); await using var r=await cmd.ExecuteReaderAsync(token); return await r.ReadAsync(token)?map(r):null; }
    private async Task<SqlConnection> OpenAsync(CancellationToken token){var c=new SqlConnection(_connectionString);await c.OpenAsync(token);return c;}
    private static SqlCommand Procedure(SqlConnection c,string name)=>new(name,c){CommandType=CommandType.StoredProcedure,CommandTimeout=60};
    private static void Add(SqlCommand c,string n,object? v)=>c.Parameters.AddWithValue(n,v??DBNull.Value);
    private static int I(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?0:Convert.ToInt32(r[n]); private static long Long(SqlDataReader r,string n)=>Convert.ToInt64(r[n]); private static long? LongNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Convert.ToInt64(r[n]); private static int? IntNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Convert.ToInt32(r[n]); private static decimal? DecNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Convert.ToDecimal(r[n]); private static string S(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?string.Empty:Convert.ToString(r[n])??string.Empty; private static string? SNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Convert.ToString(r[n]); private static bool B(SqlDataReader r,string n)=>!r.IsDBNull(r.GetOrdinal(n))&&Convert.ToBoolean(r[n]); private static DateTime? Date(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:DateTime.SpecifyKind(Convert.ToDateTime(r[n]),DateTimeKind.Unspecified); private static DateTimeOffset Utc(SqlDataReader r,string n)=>new(DateTime.SpecifyKind(Convert.ToDateTime(r[n]),DateTimeKind.Utc)); private static DateTimeOffset? UtcNullable(SqlDataReader r,string n)=>r.IsDBNull(r.GetOrdinal(n))?null:Utc(r,n);
}
