FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY DBAPulse.sln .
COPY src ./src
RUN dotnet restore src/DBAPulse.Api/DBAPulse.Api.csproj
RUN dotnet publish src/DBAPulse.Api/DBAPulse.Api.csproj -c Release -o /out --no-restore
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "DBAPulse.Api.dll"]
