import { useEffect, useState } from 'react';
import { Box, Alert, Button, FormControlLabel, MenuItem, Paper, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';

const api = import.meta.env.VITE_API_BASE_URL || '/api';
type AiSettings = { provider: string; model: string; baseUrl: string; protocol: string; isConfigured: boolean };
type SmtpSettings = { host: string; port: number; security: string; username: string; fromEmail: string; fromName: string; isConfigured: boolean };
type AdSettings = { domain: string; host: string; port: number; baseDn: string; username: string; useSsl: boolean; enabled: boolean; isConfigured: boolean };
type ServerSetting = { serverId: number; serverName: string; instanceName: string; edition: string; isActive: boolean; collectionIntervalMinutes: number; capacityIntervalMinutes: number };

export default function SettingsView() {
  const [tab, setTab] = useState(0);
  const [ai, setAi] = useState<AiSettings>({ provider: 'gemini', model: 'gemini-flash-latest', baseUrl: 'https://generativelanguage.googleapis.com/v1beta', protocol: 'gemini', isConfigured: false });
  const [smtp, setSmtp] = useState<SmtpSettings>({ host: '', port: 587, security: 'starttls', username: '', fromEmail: '', fromName: 'DBA Pulse', isConfigured: false });
  const [ad, setAd] = useState<AdSettings>({ domain: '', host: '', port: 389, baseDn: '', username: '', useSsl: false, enabled: false, isConfigured: false });
  const [servers, setServers] = useState<ServerSetting[]>([]);
  const [apiKey, setApiKey] = useState(''); const [smtpPassword, setSmtpPassword] = useState(''); const [adPassword, setAdPassword] = useState('');
  const [saved, setSaved] = useState(''); const [error, setError] = useState(''); const [testing, setTesting] = useState(false);

  useEffect(() => {
    Promise.all([fetch(`${api}/settings/ai`).then(r => r.json()), fetch(`${api}/settings/smtp`).then(r => r.json()), fetch(`${api}/settings/ad`).then(r => r.json()), fetch(`${api}/settings/servers`).then(r => r.json())])
      .then(([aiSettings, smtpSettings, adSettings, serverSettings]) => { setAi(aiSettings); setSmtp(smtpSettings); setAd(adSettings); setServers(serverSettings); })
      .catch(() => setError('Settings could not be loaded.'));
  }, []);
  const test = async (kind: 'ai' | 'smtp' | 'ad') => { setTesting(true); setSaved(''); setError(''); try { const r = await fetch(`${api}/settings/${kind}/test`, { method: 'POST' }); const result = await r.json(); if (result.success) setSaved(result.message); else setError(result.message); } catch { setError(`${kind.toUpperCase()} connection test failed.`); } finally { setTesting(false); } };
  const save = async (kind: 'ai' | 'smtp' | 'ad', body: unknown, clear: () => void, message: string) => { setSaved(''); setError(''); const r = await fetch(`${api}/settings/${kind}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) { setError(`${kind.toUpperCase()} settings could not be saved.`); return; } const value = await r.json(); if (kind === 'ai') setAi(value); if (kind === 'smtp') setSmtp(value); if (kind === 'ad') setAd(value); clear(); setSaved(message); };
  const updateServer = async (server: ServerSetting, update: Partial<ServerSetting>) => { setError(''); const r = await fetch(`${api}/settings/servers/${server.serverId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(update) }); if (!r.ok) { setError('Server settings could not be updated.'); return; } setServers(rows => rows.map(row => row.serverId === server.serverId ? { ...row, ...update } : row)); setSaved(`${server.serverName} settings saved.`); };  return <Stack spacing={2}><Typography variant="h4">Settings</Typography><Typography color="text.secondary">Configure integrations and server scope used by DBA Pulse.</Typography>{error && <Alert severity="error">{error}</Alert>}{saved && <Alert severity="success">{saved}</Alert>}<Paper className="panel settings-panel"><Tabs value={tab} onChange={(_, value) => { setTab(value); setError(''); setSaved(''); }}><Tab label="AI Settings" /><Tab label="SMTP Settings" /><Tab label="AD Settings" /><Tab label="Server Settings" /></Tabs>
    {tab === 0 && <Stack spacing={2} sx={{ pt: 2 }}><Typography variant="h6">AI Provider</Typography><TextField select label="Provider" value={ai.provider} onChange={e => setAi({ ...ai, provider: e.target.value })}><MenuItem value="none">Disabled</MenuItem><MenuItem value="openai">OpenAI</MenuItem><MenuItem value="onprem">On-prem OpenAI-compatible API</MenuItem><MenuItem value="gemini">Google Gemini</MenuItem></TextField><TextField label="Model" value={ai.model} onChange={e => setAi({ ...ai, model: e.target.value })} /><TextField label="Base URL" value={ai.baseUrl} onChange={e => setAi({ ...ai, baseUrl: e.target.value })} /><TextField select label="Protocol" value={ai.protocol} onChange={e => setAi({ ...ai, protocol: e.target.value })}><MenuItem value="responses">Responses API</MenuItem><MenuItem value="chat-completions">Chat Completions</MenuItem><MenuItem value="gemini">Gemini generateContent</MenuItem></TextField><TextField type="password" label={ai.isConfigured ? 'API key (leave blank to keep current)' : 'API key'} value={apiKey} onChange={e => setApiKey(e.target.value)} autoComplete="new-password" /><Stack direction="row" spacing={1}><Button variant="contained" onClick={() => save('ai', { ...ai, apiKey }, () => setApiKey(''), 'AI settings saved. API key is never displayed.')}>Save AI settings</Button><Button variant="outlined" onClick={() => test('ai')} disabled={testing}>{testing ? 'Testing…' : 'Test API connection'}</Button></Stack></Stack>}
    {tab === 1 && <Stack spacing={2} sx={{ pt: 2 }}><Typography variant="h6">SMTP Server</Typography><TextField label="SMTP host" value={smtp.host} onChange={e => setSmtp({ ...smtp, host: e.target.value })} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth type="number" label="Port" value={smtp.port} onChange={e => setSmtp({ ...smtp, port: Number(e.target.value) })} /><TextField fullWidth select label="Security" value={smtp.security} onChange={e => setSmtp({ ...smtp, security: e.target.value })}><MenuItem value="starttls">STARTTLS</MenuItem><MenuItem value="ssl">SSL/TLS</MenuItem><MenuItem value="none">None</MenuItem></TextField></Stack><TextField label="Username" value={smtp.username} onChange={e => setSmtp({ ...smtp, username: e.target.value })} /><TextField type="password" label={smtp.isConfigured ? 'Password (leave blank to keep current)' : 'Password'} value={smtpPassword} onChange={e => setSmtpPassword(e.target.value)} autoComplete="new-password" /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="From email" value={smtp.fromEmail} onChange={e => setSmtp({ ...smtp, fromEmail: e.target.value })} /><TextField fullWidth label="From name" value={smtp.fromName} onChange={e => setSmtp({ ...smtp, fromName: e.target.value })} /></Stack><Stack direction="row" spacing={1}><Button variant="contained" onClick={() => save('smtp', { ...smtp, password: smtpPassword }, () => setSmtpPassword(''), 'SMTP settings saved. Password is never displayed.')}>Save SMTP settings</Button><Button variant="outlined" onClick={() => test('smtp')} disabled={testing}>{testing ? 'Testing…' : 'Test SMTP connection'}</Button></Stack></Stack>}
    {tab === 2 && <Stack spacing={2} sx={{ pt: 2 }}><Typography variant="h6">Active Directory</Typography><FormControlLabel control={<Switch checked={ad.enabled} onChange={e => setAd({ ...ad, enabled: e.target.checked })} />} label="Enable Active Directory integration" /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="Domain" value={ad.domain} onChange={e => setAd({ ...ad, domain: e.target.value })} /><TextField fullWidth label="AD server / LDAP host" value={ad.host} onChange={e => setAd({ ...ad, host: e.target.value })} /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth type="number" label="Port" value={ad.port} onChange={e => setAd({ ...ad, port: Number(e.target.value) })} /><TextField fullWidth label="Base DN" value={ad.baseDn} onChange={e => setAd({ ...ad, baseDn: e.target.value })} /></Stack><TextField label="Username" value={ad.username} onChange={e => setAd({ ...ad, username: e.target.value })} /><TextField type="password" label={ad.isConfigured ? 'Password (leave blank to keep current)' : 'Password'} value={adPassword} onChange={e => setAdPassword(e.target.value)} autoComplete="new-password" /><FormControlLabel control={<Switch checked={ad.useSsl} onChange={e => setAd({ ...ad, useSsl: e.target.checked })} />} label="Use LDAPS / SSL" /><Stack direction="row" spacing={1}><Button variant="contained" onClick={() => save('ad', { ...ad, password: adPassword }, () => setAdPassword(''), 'AD settings saved. Password is never displayed.')}>Save AD settings</Button><Button variant="outlined" onClick={() => test('ad')} disabled={testing}>{testing ? 'Testing…' : 'Test AD connection'}</Button></Stack></Stack>}
    {tab === 3 && <Stack spacing={2} sx={{ pt: 2 }}><Typography variant="h6">Server Scope &amp; Collection</Typography><Typography variant="body2" color="text.secondary">Inactive servers are hidden from lists and reports and skipped by the collector. Collection intervals are configured per server in minutes.</Typography><Stack spacing={1}>{servers.map(server => <Paper key={server.serverId} variant="outlined" sx={{ p: 1.5 }}><Stack spacing={1}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ xs: 'flex-start', sm: 'center' }} spacing={1}><Box><Typography variant="subtitle2">{server.serverName}</Typography><Typography variant="caption" color="text.secondary">{server.instanceName} · {server.edition}</Typography></Box><FormControlLabel control={<Switch checked={server.isActive} onChange={e => updateServer(server, { isActive: e.target.checked })} />} label={server.isActive ? 'Active' : 'Inactive'} /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField size="small" type="number" label="Collection interval (min)" value={server.collectionIntervalMinutes} inputProps={{ min: 1, max: 1440 }} onChange={e => setServers(rows => rows.map(row => row.serverId === server.serverId ? { ...row, collectionIntervalMinutes: Number(e.target.value) } : row))} /><TextField size="small" type="number" label="Capacity interval (min)" value={server.capacityIntervalMinutes} inputProps={{ min: 1, max: 1440 }} onChange={e => setServers(rows => rows.map(row => row.serverId === server.serverId ? { ...row, capacityIntervalMinutes: Number(e.target.value) } : row))} /><Button variant="outlined" onClick={() => updateServer(server, { collectionIntervalMinutes: server.collectionIntervalMinutes, capacityIntervalMinutes: server.capacityIntervalMinutes })}>Save intervals</Button></Stack></Stack></Paper>)}</Stack></Stack>}
  </Paper></Stack>;
}