CREATE OR ALTER PROCEDURE dbo.usp_Capacity_Overview AS
BEGIN
 SET NOCOUNT ON;
 ;WITH x AS (SELECT c.DatabaseId,c.CollectedAtUtc,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN 0 ELSE c.AllocatedSizeMb END) DataMb,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN c.AllocatedSizeMb ELSE 0 END) LogMb FROM dbo.CapacitySnapshots c WHERE c.DatabaseId IS NOT NULL GROUP BY c.DatabaseId,c.CollectedAtUtc), latest AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY DatabaseId ORDER BY CollectedAtUtc DESC) rn FROM x), previous AS (SELECT a.DatabaseId,a.DataMb+a.LogMb TotalMb, b.DataMb+b.LogMb PreviousMb FROM latest a OUTER APPLY(SELECT TOP(1) DataMb,LogMb FROM x z WHERE z.DatabaseId=a.DatabaseId AND z.CollectedAtUtc<=DATEADD(DAY,-30,a.CollectedAtUtc) ORDER BY z.CollectedAtUtc DESC)b WHERE a.rn=1)
 SELECT SUM(CASE WHEN rn=1 THEN DataMb+LogMb ELSE 0 END) TotalDatabaseSizeMb, SUM(CASE WHEN rn=1 AND PreviousMb IS NOT NULL THEN DataMb+LogMb-PreviousMb ELSE 0 END) Growth30dMb, 0 DatabaseWarningCount,0 DatabaseCriticalCount,0 VolumeWarningCount,0 VolumeCriticalCount,0 ForecastableDatabaseCount,SUM(CASE WHEN rn=1 AND PreviousMb IS NULL THEN 1 ELSE 0 END) InsufficientDataCount,CAST(NULL AS decimal(19,2)) NearestExhaustionDays FROM (SELECT l.*,p.PreviousMb FROM latest l LEFT JOIN previous p ON p.DatabaseId=l.DatabaseId) q;
END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Capacity_Databases @Status nvarchar(30)=NULL,@ServerId int=NULL,@ForecastStatus nvarchar(30)=NULL,@PageNumber int=1,@PageSize int=50,@DatabaseId int=NULL AS
BEGIN
 SET NOCOUNT ON; SET @PageSize=CASE WHEN @PageSize>100 THEN 100 WHEN @PageSize<1 THEN 1 ELSE @PageSize END;
 ;WITH x AS (SELECT c.DatabaseId,c.CollectedAtUtc,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN 0 ELSE c.AllocatedSizeMb END) DataMb,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN c.AllocatedSizeMb ELSE 0 END) LogMb FROM dbo.CapacitySnapshots c WHERE c.DatabaseId IS NOT NULL GROUP BY c.DatabaseId,c.CollectedAtUtc), d AS (SELECT x.*,CAST(x.CollectedAtUtc AS date) DayValue,ROW_NUMBER() OVER(PARTITION BY x.DatabaseId,CAST(x.CollectedAtUtc AS date) ORDER BY x.CollectedAtUtc DESC) rn FROM x), daily AS (SELECT * FROM d WHERE rn=1), current_row AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY DatabaseId ORDER BY CollectedAtUtc DESC) current_rn FROM daily), metrics AS (SELECT c.DatabaseId,c.DataMb,c.LogMb,c.DataMb+c.LogMb TotalMb,c.CollectedAtUtc,COUNT(s.DayValue) SampleCount,DATEDIFF(DAY,MIN(s.DayValue),MAX(s.DayValue)) HistoryDays FROM current_row c JOIN daily s ON s.DatabaseId=c.DatabaseId WHERE c.current_rn=1 GROUP BY c.DatabaseId,c.DataMb,c.LogMb,c.CollectedAtUtc), refs AS (SELECT m.*,r7.TotalMb Ref7,r30.TotalMb Ref30,r90.TotalMb Ref90 FROM metrics m OUTER APPLY(SELECT TOP(1) DataMb+LogMb TotalMb FROM daily WHERE DatabaseId=m.DatabaseId AND DayValue<=DATEADD(DAY,-7,CAST(m.CollectedAtUtc AS date)) ORDER BY DayValue DESC)r7 OUTER APPLY(SELECT TOP(1) DataMb+LogMb TotalMb FROM daily WHERE DatabaseId=m.DatabaseId AND DayValue<=DATEADD(DAY,-30,CAST(m.CollectedAtUtc AS date)) ORDER BY DayValue DESC)r30 OUTER APPLY(SELECT TOP(1) DataMb+LogMb TotalMb FROM daily WHERE DatabaseId=m.DatabaseId AND DayValue<=DATEADD(DAY,-90,CAST(m.CollectedAtUtc AS date)) ORDER BY DayValue DESC)r90)
 SELECT db.Id DatabaseId,db.DatabaseName,s.ServerName,m.DataMb CurrentDataSizeMb,m.LogMb CurrentLogSizeMb,m.TotalMb CurrentTotalSizeMb,CASE WHEN Ref7 IS NULL THEN NULL ELSE m.TotalMb-Ref7 END Growth7dMb,CASE WHEN Ref30 IS NULL THEN NULL ELSE m.TotalMb-Ref30 END Growth30dMb,CASE WHEN Ref90 IS NULL THEN NULL ELSE m.TotalMb-Ref90 END Growth90dMb,CAST(NULL AS decimal(19,4)) GrowthRateMbPerDay,CAST(NULL AS decimal(19,2)) Forecast30dMb,CAST(NULL AS decimal(19,2)) Forecast90dMb,CAST(NULL AS decimal(19,6)) RSquared,m.SampleCount,m.HistoryDays,CASE WHEN m.SampleCount<7 OR m.HistoryDays<7 THEN 'InsufficientData' ELSE 'Usable' END ForecastStatus,CASE WHEN m.SampleCount<7 OR m.HistoryDays<7 THEN 'InsufficientData' ELSE 'Healthy' END CapacityStatus,m.CollectedAtUtc LastCollectedAtUtc,CASE WHEN m.CollectedAtUtc<DATEADD(HOUR,-3,SYSUTCDATETIME()) THEN 'Stale' ELSE 'Fresh' END DataFreshness FROM refs m JOIN dbo.Databases db ON db.Id=m.DatabaseId JOIN dbo.Servers s ON s.Id=db.ServerId WHERE (@DatabaseId IS NULL OR db.Id=@DatabaseId) AND (@ServerId IS NULL OR db.ServerId=@ServerId) AND (@ForecastStatus IS NULL OR @ForecastStatus=(CASE WHEN m.SampleCount<7 OR m.HistoryDays<7 THEN 'InsufficientData' ELSE 'Usable' END)) ORDER BY db.DatabaseName OFFSET (@PageNumber-1)*@PageSize ROWS FETCH NEXT @PageSize ROWS ONLY;
 SELECT COUNT(*) TotalCount FROM dbo.Databases WHERE (@DatabaseId IS NULL OR Id=@DatabaseId);
END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Capacity_DatabaseHistory @DatabaseId int,@Days int=30 AS
BEGIN
 SET NOCOUNT ON; SET @Days=CASE WHEN @Days IN(7,30,90,180,365) THEN @Days ELSE 30 END;
 ;WITH x AS (SELECT c.CollectedAtUtc,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN 0 ELSE c.AllocatedSizeMb END) DataMb,SUM(CASE WHEN c.FileType LIKE '%LOG%' THEN c.AllocatedSizeMb ELSE 0 END) LogMb FROM dbo.CapacitySnapshots c WHERE c.DatabaseId=@DatabaseId AND c.CollectedAtUtc>=DATEADD(DAY,-@Days,SYSUTCDATETIME()) GROUP BY c.CollectedAtUtc)
 SELECT CollectedAtUtc,DataMb DataSizeMb,LogMb LogSizeMb,DataMb+LogMb TotalSizeMb,CAST(NULL AS decimal(19,2)) ForecastTotalSizeMb,'Actual' SeriesType FROM x ORDER BY CollectedAtUtc;
END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Capacity_Volumes @Status nvarchar(30)=NULL,@ServerId int=NULL,@ForecastStatus nvarchar(30)=NULL,@PageNumber int=1,@PageSize int=50,@VolumeId nvarchar(512)=NULL AS
BEGIN
 SET NOCOUNT ON; SET @PageSize=CASE WHEN @PageSize>100 THEN 100 WHEN @PageSize<1 THEN 1 ELSE @PageSize END;
 ;WITH latest AS (SELECT v.*,ROW_NUMBER() OVER(PARTITION BY v.ServerId,v.VolumeId ORDER BY v.CollectedAtUtc DESC) rn FROM dbo.VolumeCapacitySnapshots v)
 SELECT v.Id,v.ServerId,s.ServerName,v.VolumeId,v.TotalBytes,v.AvailableBytes,CAST(v.AvailableBytes*100.0/NULLIF(v.TotalBytes,0) AS decimal(9,2)) FreePercent,CAST(NULL AS decimal(19,2)) GrowthBytesPerDay,CAST(NULL AS decimal(19,2)) EstimatedExhaustionDays,'InsufficientData' ForecastStatus,CASE WHEN v.AvailableBytes*100.0/NULLIF(v.TotalBytes,0)<=10 THEN 'Critical' WHEN v.AvailableBytes*100.0/NULLIF(v.TotalBytes,0)<=15 THEN 'Warning' ELSE 'Healthy' END CapacityStatus,1 SampleCount,v.CollectedAtUtc,CASE WHEN v.CollectedAtUtc<DATEADD(HOUR,-3,SYSUTCDATETIME()) THEN 'Stale' ELSE 'Fresh' END DataFreshness FROM latest v JOIN dbo.Servers s ON s.Id=v.ServerId WHERE v.rn=1 AND (@VolumeId IS NULL OR v.VolumeId=@VolumeId) AND (@ServerId IS NULL OR v.ServerId=@ServerId) ORDER BY v.VolumeId OFFSET (@PageNumber-1)*@PageSize ROWS FETCH NEXT @PageSize ROWS ONLY;
 SELECT COUNT(*) TotalCount FROM dbo.VolumeCapacitySnapshots v WHERE NOT EXISTS (SELECT 1 FROM dbo.VolumeCapacitySnapshots newer WHERE newer.ServerId=v.ServerId AND newer.VolumeId=v.VolumeId AND (newer.CollectedAtUtc>v.CollectedAtUtc OR (newer.CollectedAtUtc=v.CollectedAtUtc AND newer.Id>v.Id))) AND (@VolumeId IS NULL OR v.VolumeId=@VolumeId);
END;
