SELECT
    ws.wait_type,
    CONVERT(bigint, ws.wait_time_ms) AS wait_time_ms,
    CONVERT(bigint, ws.signal_wait_time_ms) AS signal_wait_time_ms,
    CONVERT(bigint, ws.waiting_tasks_count) AS waiting_tasks_count,
    CONVERT(datetime2(3), si.sqlserver_start_time) AS sql_server_start_time
FROM sys.dm_os_wait_stats AS ws
CROSS JOIN sys.dm_os_sys_info AS si
WHERE ws.wait_type NOT IN
(
    N'BROKER_EVENTHANDLER', N'BROKER_RECEIVE_WAITFOR', N'BROKER_TASK_STOP',
    N'BROKER_TO_FLUSH', N'BROKER_TRANSMITTER', N'CHECKPOINT_QUEUE',
    N'CHKPT', N'CLR_AUTO_EVENT', N'CLR_MANUAL_EVENT', N'DBMIRROR_EVENTS_QUEUE',
    N'DBMIRRORING_CMD', N'DIRTY_PAGE_POLL', N'DISPATCHER_QUEUE_SEMAPHORE',
    N'EXECSYNC', N'FSAGENT', N'FT_IFTS_SCHEDULER_IDLE_WAIT', N'LAZYWRITER_SLEEP',
    N'LOGMGR_QUEUE', N'ONDEMAND_TASK_QUEUE', N'REQUEST_FOR_DEADLOCK_SEARCH',
    N'RESOURCE_QUEUE', N'SERVER_IDLE_CHECK', N'SLEEP_BPOOL_FLUSH', N'SLEEP_DBSTARTUP',
    N'SLEEP_TASK', N'SLEEP_SYSTEMTASK', N'SQLTRACE_BUFFER_FLUSH', N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP',
    N'SQLTRACE_WAIT_ENTRIES', N'WAITFOR', N'WAITFOR_TASKSHUTDOWN', N'XE_DISPATCHER_WAIT',
    N'XE_TIMER_EVENT'
)
  AND ws.wait_time_ms > 0;
